### ISSUE TITLE
Maze generation failure

### ISSUE THREAD

**Issue by AI-Avalon** [karikera/bdsx-maze-generator#1]
Hi.
I'm using 1.18.2.
I have a request and a question about how to generate a maze.
When I try to generate a maze
[maze 159936 100 159936 256 5 256 smooth_stone
maze-generator: Generating
 x223075
maze-generator: Generate Failed x223075]
The result is something like this, which generates a straightforward maze.
So it would be nice if the maze could be generated using the hole digging method.
Also, it would be very helpful if you could add the ability to execute commands from within Microla and display the correct route of the maze.
What do you think?
![Minecraft Screenshot 2021 12 16 - 19 27 25 77](https://user-images.githubusercontent.com/71456288/146355637-cfe728b2-254d-4843-a9bf-6691477f27b8.png)

**Comment by karikera** [comment]
Thanks for your issue.
it seems this issue page has multiple issues.
it would be better to make a page per issue.

this plugin is one of the example plugins and It is roughly made.
I will check it some other time.
